repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.22" # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-validate # It should be before tflint hook as it runs terraform init required by tflint
      - id: terraform-fmt
      - id: tflint
        args:
          - --module
          - --config=.tflint.hcl

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0" # Get the latest from: https://github.com/terraform-docs/terraform-docs/releases
    hooks:
      - id: terraform-docs-go
        args: ["."]

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "2.4.48" # Get the latest from: https://github.com/bridgecrewio/checkov/releases
    hooks:
      - id: checkov
        args: [--skip-check, "CKV2_GHA_1,CKV_TF_1"] #False positive for top-level permissions

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0" # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
