name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    uses: getindata/github-workflows/.github/workflows/gh-validate-pr-title.yml@v0.3.0
